### ISSUE TITLE
Stack interdependencies makes new environment impossible

### ISSUE THREAD

**Issue by kernwig** [aws-samples/amplify-photo-gallery-workshop#16]
Following the workshop step by step is fine, but if you take the end result to another computer and try to `amplify init` anew, it is impossible.

Even accounting for manually updating 😢 resource names and ARNs in the custom CloudFormation, the mutual dependency blocks initial deployment. The storage stack needs the workshopphotoprocessor ARN to set it up as a trigger, but that function can't be created until it has the storage bucket's name.

I think the solution involves:

1. In backend-config.json, set the `function`'s `dependsOn` to pull the DynamoDB name from the `api` stack and `BucketName` from the storage stack.
2. Move the S3 trigger resources into the `function` stack.

The syntax of `dependsOn` is a bit of a mystery - I can't find actual documentation.

I'd really appreciate an update to resolve this defect. 😌

**Comment by gabehollombe-aws** [comment]
Hi @kernwig  - Thanks for taking the time to try this out and to post some ideas about how to solve the issue.

Yesterday I published a new version of the workshop that updates the steps to take advantage of Amplify's new lambda trigger functionality when adding storage to an app.

I believe if you try the new workshop content all the way through, then push your `photoalbums` code dir to a git repo, then clone that, all you'll need to do is:

1. `amplify init` in the cloned repo. Don't import existing environment.
2. `amplify push`
3. Re-do steps 4 and 5 and 6 from this page of the new workshop content 
https://amplify-workshop.go-aws.com/70_generating_thumbnails/10_creating_a_photo_processor_lambda.html
4. Try using the new app. It should all be configured right at that point, I think.

Can you give that a shot and let me know how you go?

**Comment by kernwig** [comment]
Thank you @gabehollombe-aws. I noticed the new Angular CLI support for triggers and we were planning to try just that. Your updated instructions help confirm the approach. My colleague will actually be attempting this for me.

Any chance at expanding on how to remove step 6 each time? It should be possible to get the DynamoDB table nome from the API stack and bucket name from the storage stack, and pass those to the function stack. We just haven't been able to figure out how to do that within the confines of Amplify.

**Comment by igeiman** [comment]
Hi  @gabehollombe-aws. I gave the updated workshop a try and noticed a few things:
1. _amplify storage add_ is now asking if i need a trigger, which is great
2. The tutorial still suggest creating another function, workshopphotoprocessor while we actually have to update the function created as part of the storage step rather than adding a new function with _amplify function add_
3. Step that suggest updating bucket's CF to reference lambda function is redundant; s3 bucket CF already references notification Lambda as a result of step 1 above
4. _amplify push_ is failing since there is no valid dynamodb table arn and no s3 bucket at this point, all the resources are being rolled back. The only hack i found for now is to provide valid but unrelated parameters in parameters.json for Lambda, let the deployment run to completion and update later with valid values and redeploy lambda function only

**Comment by gabehollombe-aws** [comment]
@igeiman  - Thanks for this feedback. Have you looked at the workshop content in the last 4 days? I recently published an updated version and I think it addresses the issues you highlight.

**Comment by gabehollombe-aws** [comment]
Closing. I recently published a new version of the workshop that revises these steps and simplifies the CF tweaking.
