### ISSUE TITLE
When logged in as "member" graphql GetAlbum call returns empty array of photos.

### ISSUE THREAD

**Issue by andaqui** [aws-samples/amplify-photo-gallery-workshop#19]
Nice tutorial. I followed everything and got it all working except one thing. When i login as "member" user i can see the album name etc but the photos array is empty. (If i login as owner i can see the photos). Does the Photo model need to allow members as well like the Album model in the graphql schema file?? Or is something else bugging here?

**Comment by gabehollombe-aws** [comment]
Thanks for following along with the tutorial @gitsaysno --  In fact, you _did_ discover a bug.  A while back I refactored this workshop to provide additional security posturing, and those updates broke this bonus content section.

The photos are uploaded to albums under Amplify's `private` setting, which prevents any user besides the owner from accessing those uploads. Thanks for highlighting this. I'm going to pull this bonus section content since it's broken.

**Comment by andaqui** [comment]
Cool, if i wanted to get this member auth working, how would i go about it? Would it be to make a "Many-To-Many Connection" on members so both Album and Photo models have members synced and then i could add `ownerField: "members"` to Photo @auth? Or is there a better way? Thanks for your time.

**Comment by gabehollombe-aws** [comment]
Your approach won't be enough, because the current codebase uploads each photo as private to the owner. See https://aws-amplify.github.io/docs/js/storage#file-access-levels  for more info on this.  Look at the PrivatePolicy IAM policy attached to the AuthRole generated in your cloudformation stack for this app to see how it's implemented.

I haven't explored this option yet, but I think what might work is creating a new graphql query to handle listing an album's photos, to specifically be used when members try to view an album. You could implement that query with a lambda resolver that could:
1. Check to make sure that the requesting user is a member of the album in question
2. Fetch the list of photos for the album
3. Generate a presigned S3 url for each photo and return those to the client (more on this below)
4. Have the client use those presigned S3 urls to fetch the images

When creating the presigned urls, since this is happening server-side, you'd need to use a user that has rights to those files, which would mean creating a sort of admin user in the cognito user pool, giving that user IAM rights to all files in the s3 bucket that amplify uses for uploads, and using that admin user's credentials when creating the presigned urls (with some sensible timeout for the url validity).

It's a bit of work, and the reason why I wasn't able to quickly give you an answer before.

**Comment by andaqui** [comment]
Thanks for the response. Sounds more tricky, will try it out.
