### ISSUE TITLE
Error when running S3Trigger

### ISSUE THREAD

**Issue by GattN1** [aws-samples/amplify-photo-gallery-workshop#30]
`LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.`

Coming up with this error in my CloudWatch Logs. I'm assuming it's a permissions error somewhere but I'm not sure where.

**Comment by gabehollombe-aws** [comment]
Hmm...

Any other output from the Lambda S3 Trigger function in cloudwatch during executions?  If not, could you drop some log lines in and see if you can pinpoint where the issue is?  

One thought: are you doing this in Cloud9 or are you deploying (amplify push) from your own development workstation? If it's the latter, you probably need to re-install the npm sharp dependency as to run on amazon linux. Let me know and I can provide instructions if this is the case.

**Comment by GattN1** [comment]
Running on C9. Although I'm also having an issue where photos are uploading to private/upload, not public/uploads.

**Comment by GattN1** [comment]
Just started over and there's no errors but also no photo shows up in app, and while it shows up in s3, there's no thumbnail.

**Comment by gabehollombe-aws** [comment]
@GattN1  Thanks for filing this.  I was able to reproduce the issue when I got to the Generating Thumbnails section of the workshop.  

Luckily, I was able to identify the issue and re-deploy a fix with updated instructional content.

Please see the new info on this page: https://amplify-workshop.go-aws.com/70_generating_thumbnails/10_processing_photos_with_the_s3_trigger_lambda_function.html

The fix had to do with the last few lines in the big copy/paste block on that page's instructions. Amplify auto generates IAM role names and these can conflict, so we need to ensure our storage and s3 trigger cloudformation templates have unique role names.

Please re-try with the latest deployed instructions on that page and let me know if your problem persists!
