### ISSUE TITLE
"Unhandled Rejection (Error): Region is missing" when uploading a photo to an album

### ISSUE THREAD

**Issue by nerdyness** [aws-samples/amplify-photo-gallery-workshop#50]
Hi there,

While running through the workshop I got until [Managing Photos](https://amplify-workshop.go-aws.com/60_managing_photos/40_upload_photos_consolidated.html) and then I'm getting the below error:
<img width="1165" alt="Screen Shot 2020-11-09 at 15 59 33 " src="https://user-images.githubusercontent.com/696600/98557633-bdd89200-22a4-11eb-8d27-604a0d52d58b.png">

I've tried things like setting various environment variables when starting the npm server:
```
$ AWS_REGION=eu-west-1 AWS_DEFAULT_CONFIG=eu-west-1 npm start
```
on top of the profile in ~/.aws/config which should already define the region:
```
$ cat ~/.aws/config 
[default]
region=eu-west-1
```

I'm still getting the error and am not sure where to go from here. Thanks krisstef@

**Comment by swyxio** [comment]
hey! i tried going thru this workshop today and did not run into this issue. can you share your `aws-exports.js`? perhaps it is misconfigured somehow. since you are also at AWS you have probably ruled out all the normal causes of these issues.

i did a search of the amplify repo and only found one match - https://github.com/aws-amplify/amplify-js/issues/5876 seems to have been fixed with `aws-amplify@3.0.13`. if i'm not wrong, this workshop had you install ` aws-amplify@3.0.7`, perhaps it just takes a version bump

**Comment by nerdyness** [comment]
I did double-check my work at the time but in a burner account which is now gone. I don't have the time to look into this further at the moment so I'm going to close this for now and re-open if future tests confirm this is a problem. Thanks for looking into this for me. @sw-yx

**Comment by swyxio** [comment]
such is life in tech support 😂
