### ISSUE TITLE
workshop fails after adding-amplify-npm-dependencies step

### ISSUE THREAD

**Issue by abulatkin** [aws-samples/amplify-photo-gallery-workshop#57]
Is this workshop up to date? When do this step https://amplify-workshop.go-aws.com/30_adding_auth/20_adding_auth_front.html#adding-amplify-npm-dependencies
I get a bunch of warnings like tese 
npm WARN aws-amplify-react@3.1.9 requires a peer of @aws-amplify/api@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN aws-amplify-react@3.1.9 requires a peer of @aws-amplify/auth@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN aws-amplify-react@3.1.9 requires a peer of @aws-amplify/core@^2.0.0 but none is installed. You must install peer dependencies yourself.

and errors like these
npm ERR! code ENOSPC
npm ERR! syscall mkdir
npm ERR! path /home/ec2-user/environment/photoalbums/node_modules/.staging/@aws-sdk/credential-provider-env-5945d4e1
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, mkdir '/home/ec2-user/environment/photoalbums/node_modules/.staging/@aws-sdk/credential-provider-env-5945d4e1'
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.

I followed all the steps and used t2.medium for Cloud9 environment

**Comment by edwardchchen** [comment]
I think this problem is caused by that your Cloud9 instance has ran out of storage (default is 2GB). You need to fix this problem by resizing your Cloud9 instance. Please refer to the section (Resize an Amazon EBS volume used by an environment ) of the link below.
https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html#move-environment-resize
